# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.05881667, 0.07666378, 0.02304611],
       [0.34705857, 0.19736988, 0.60310956],
       [0.43985037, 0.12758588, 0.33329056],
       [0.89541909, 0.17852092, 0.99962573],
       [0.35696521, 0.98047957, 0.99490735],
       [0.92727395, 0.56100926, 0.22274138],
       [0.91362336, 0.93143126, 0.96201284],
       [0.7623531 , 0.83212179, 0.13197637],
       [0.74820801, 0.56205758, 0.40430671],
       [0.59374375, 0.32386755, 0.54185391],
       [0.91070908, 0.59813975, 0.03473574],
       [0.34877823, 0.34017292, 0.99035332],
       [0.80454195, 0.73766039, 0.59540862],
       [0.42006499, 0.43540735, 0.44883262],
       [0.16616708, 0.81267619, 0.06690349],
       [0.09348819, 0.69561987, 0.55469158],
       [0.5870353 , 0.4329311 , 0.74643704],
       [0.68547385, 0.62323495, 0.26939628],
       [0.49639073, 0.60443411, 0.44358784],
       [0.80112162, 0.03234293, 0.10647002],
       [0.83110358, 0.2362557 , 0.83946473],
       [0.6420801 , 0.30607862, 0.42329017],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.92727395, 0.56100926, 0.22274138],
       [0.74820801, 0.56205758, 0.40430671]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
clusters = vq(data, clust_centers)
clusters

(array([1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1], dtype=int32),
 array([0.92532546, 0.57744313, 0.53748804, 0.72330921, 0.82277397,
        0.        , 0.68908293, 0.33005936, 0.        , 0.3154567 ,
        0.19235173, 0.74312018, 0.26557447, 0.35454292, 0.71792915,
        0.68491791, 0.39962914, 0.16086973, 0.25836161, 0.55580709,
        0.54989185, 0.27775661, 0.68593624, 0.20691061, 0.59257729,
        0.40250723, 0.41177392, 0.23051174, 0.65090095, 0.72645442]))

In [6]:
labels = clusters[0]
labels

array([1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1], dtype=int32)

In [10]:
import chart_studio.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply

In [11]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters')


/opt/anaconda3/lib/python3.7/site-packages/plotly/offline/offline.py:563: UserWarning:

Your filename `Clusters` didn't end with .html. Adding .html to the end of your file.



'Clusters.html'

In [12]:
from scipy.cluster.vq import kmeans

In [13]:
kmeans(data, clust_centers)

(array([[0.59480931, 0.5962024 , 0.18368137],
        [0.55155552, 0.40924095, 0.69814459]]),
 0.3813315738289043)

In [14]:
kmeans(data, 2)

(array([[0.48231845, 0.33529177, 0.64588016],
        [0.67084783, 0.66736136, 0.28015951]]),
 0.3724574551672519)